### ISSUE TITLE
Tries to move files to / if XDG_CONFIG_HOME is not set.

### ISSUE THREAD

**Issue by baryluk** [doron-cohen/antidot#73] opened 2020-12-12 23:02 UTC
Downloaded v0.3.0 for amd64, done `antidot update`, then tried to run it:

```
user@debian:~$ ./antidot-linux-amd64 clean
Rule gnupg:
  MOVE   /home/user/.gnupg → /gnupg
  EXPORT GNUPGHOME="${XDG_DATA_HOME}/gnupg"
? Apply rule gnupg? Yes
Failed to run rule gnupg: rename /home/user/.gnupg /gnupg: permission denied

Rule kde:
  MOVE   /home/user/.kde → /kde
  EXPORT KDEHOME="${XDG_CONFIG_HOME}/kde"
? Apply rule kde? (y/N) 

Rule less:
  MOVE   /home/user/.lesshst → /less/history
  EXPORT LESSHISTFILE="${XDG_CACHE_HOME}/less/history"
  EXPORT LESSKEY="${XDG_CONFIG_HOME}/less/lesskey"
? Apply rule less? (y/N) 

```

That looks very wrong.

BTW. I do not have `XDG_CONFIG_HOME` actually set.

antidot should detect that and not do silly things.

**Comment by doron-cohen** [comment] 2020-12-13 19:23
This is a duplicate of #37 . The fix is in the [latest release](https://github.com/doron-cohen/antidot/releases/tag/v0.4.0). It will use the defaults for your platform if any of the XDG vars are not detected (and will print a warning message).

I am more concerned about antidot not detecting the variables. Please check the latest release and make sure the variables are set. If this behavior continues I would appreciate it if you reopen this issue or open a new one.

**Comment by baryluk** [comment] 2020-12-13 19:38
Yes, but `antidot init` produced really wrong output. So wrong, that if accidently put in .bashrc would break the system.

```
user@debian:~$ ./antidot-linux-amd64 init
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"/home/user/.config"}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-"/home/user/.cache"}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-"/home/user/.local/share"}"

source /home/user/.local/share/antidot/env.sh
source /home/user/.local/share/antidot/alias.sh
user@debian:~$ 

user@debian:~$ $(./antidot-linux-amd64 init)
bash: export: `/home/user/.local/share/antidot/env.sh': not a valid identifier
bash: export: `/home/user/.local/share/antidot/alias.sh': not a valid identifier
user@debian:~$

user@debian:~$ env | grep XDG.*HOME
XDG_DATA_HOME="${XDG_DATA_HOME:-"/home/user/.local/share"}"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"/home/user/.config"}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-"/home/user/.cache"}"
user@debian:~$ 
```


Notice, that the $... wasn't actually evaluated to the value. This is because `}` wasn't properly closed before end of string.

I don't think you need to quote anything again in there, 

```
XDG_DATA_HOME="${XDG_DATA_HOME:-/home/user/.local/share}"
```

should be enough (and for other vars), and work fine, even if path at the right has spaces, etc.

**Comment by doron-cohen** [comment] 2020-12-13 19:48
Thanks for that. I dont test shel integration yet and I can see its more important than I thought. I will fix this by tomorrow.

**Comment by doron-cohen** [comment] 2020-12-14 08:44
fixed in https://github.com/doron-cohen/antidot/releases/tag/v0.4.1

**Closed by doron-cohen** 2020-12-14 08:44 UTC

**Comment by baryluk** [comment] 2020-12-14 10:02
@doron-cohen thanks this appears to mostly fix things for me.

`$(./antidot init)` doesn't work, but using `eval $(./antidot init)` fixes this, and makes it work. Worth updating README with that. This is with bash 5.1.0

**Comment by doron-cohen** [comment] 2020-12-14 20:37
This is extremely weird. This is actually a double eval if I understand correctly...
